site_name: Gale Documentation
site_url: https://pherngpy.github.io/
nav:
    - Home: index.md
    - About: about.md
theme: 
    palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode    
    - accent: cyan
    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    name: 'material'
extra:
    generator: false
plugins:
  - search:
      lang: 'en'


