site_name: Gale Documentation
site_url: https://pherngpy.github.io/
nav:
    - Home: index.md
    - About: about.md
theme: 
    name: 'material'
features:
    - search.suggest
    - search.highlight
    - search.share
extra:
    generator: false



