site_name: Gale Documentation
site_url: https://pherngpy.github.io/
nav:
    - Home: index.md
    - About: about.md
theme: 
    features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    name: 'material'
extra:
    generator: false
plugins:
  - search:
      lang: 'en'


